smarter/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from smarter.base import views as base_views

urlpatterns = [
    url(r'^$', base_views.home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^category/add$', base_views.create_category, name='create-category'),
    url(r'^document/all$', base_views.all_documents, name='all_documents'),
    url(r'^template/add$', base_views.create_template_format,
        name='create-template'),
    url(r'^get_template/(?P<category>[-\w]+)$', base_views.get_all_formats,
        name='all_template_formats_json'),
    url(r'^upload-document$', base_views.upload_document,
        name='upload_document'),
    url(r'^document/(?P<unique_id>[-\w]+)$', base_views.particular_document,
        name='particular_document'),
    url(r'^document/preview/(?P<unique_id>[-\w]+)$', base_views.document_preview,
        name='preview_document'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^document/(?P<unique_id>[-\w]+)/(?P<element>[-\w]+)$',
        base_views.get_element_coordinates,
        name='get_element_coordinates'),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

smarter/base/models.py
from __future__ import absolute_import, unicode_literals

import uuid

from django.db import models
from autoslug import AutoSlugField


class Category(models.Model):
    """
    List of categories a.k.a. Projects.
    """
    category_name = models.CharField(max_length=255,
                                     verbose_name="Name of the Category",
                                     unique=True)
    description = models.TextField(default="", blank=True)
    slug = AutoSlugField(populate_from="category_name", unique=True)

    def __str__(self):
        return self.category_name


class TemplateFormat(models.Model):
    """
    List of template formats. e.g. Bill for CCD, Barista, etc.
    """
    category = models.ForeignKey(Category,
                                 verbose_name="Category of the Format")
    template_name = models.CharField(max_length=225,
                                     verbose_name="Name of template format",
                                     unique=True)
    slug = AutoSlugField(populate_from="template_name", unique=True)

    def __str__(self):
        return self.template_name


class TemplateElement(models.Model):
    """
    List of elements for a given template type
    """
    template = models.ForeignKey(TemplateFormat,
                                 verbose_name="Base Format of the element")
    element_name = models.CharField(max_length=255,
                                    verbose_name="Name of the Element")

    def __str__(self):
        return self.element_name

    def get_element_name(self):
        """Returns the name of the element"""
        return self.element_name

    def get_template_name(self):
        """Returns the name of the template for which this element exist"""
        return self.template.template_name

    class Meta:
        unique_together = ('template', 'element_name')


class Document(models.Model):
    """
    Document whose elements are to be extracted
    """
    id = models.UUIDField(primary_key=True,
                          default=uuid.uuid4, editable=False)
    template_format = models.ForeignKey(TemplateFormat)
    document_name = models.CharField(max_length=255,
                                     verbose_name='name of document')
    document = models.FileField(upload_to="documents")
    element = models.ManyToManyField(TemplateElement,
                                     through='ExtractedElements')
    slug = AutoSlugField(populate_from="document_name", unique=True)
    image_resolution_x = models.IntegerField(blank=True, null=True)
    image_resolution_y = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.document_name

    def get_template_format(self):
        """Get the format of the template that this document has"""
        return self.template_format.template_name

    def get_all_elements_name(self):
        """Get name of all elements for the given document"""
        return self.element_set.all().values("element_name", flat=True)

    def count_number_of_elements(self):
        """
        Count number of template elements that are selected for this document
        """
        return self.element_set.all().count()


class ExtractedElements(models.Model):
    """
    List of all extracted elements along with their co-ordinates
    in ratio of their position to the image resolution
    """
    document = models.ForeignKey(Document)
    element = models.ForeignKey(TemplateElement)
    x1_coordinate = models.FloatField(blank=True, null=True)
    y1_coordinate = models.FloatField(blank=True, null=True)
    x2_coordinate = models.FloatField(blank=True, null=True)
    y2_coordinate = models.FloatField(blank=True, null=True)
    block_height = models.FloatField(blank=True, null=True)
    block_width = models.FloatField(blank=True, null=True)

    def __str__(self):
        return "Element %s of document  %s" % (self.element.element_name,
                                               self.document.document_name)

smarter/base/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.http import JsonResponse, HttpResponseRedirect
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Avg
from django.db import IntegrityError

from .models import (Category,
                     TemplateFormat,
                     TemplateElement,
                     Document,
                     ExtractedElements)

from .forms import CreateCategoryForm, TemplateFormatForm, DocumentForm
from .serializers import get_templates_for_category

import json


def home(request):
    """
    View for home page. 
    """
    return render_to_response("home.html", {},
                              context_instance=RequestContext(request))


def get_all_formats(request, category):
    """
    View to get all template formats that exist for the particular category
    """
    try:
        category = Category.objects.get(slug=category)
    except Category.DoesNotExist:
        message = "Invalid category selected"
        return JsonResponse({"error": "true", "message": message})
    all_templates = get_templates_for_category(category)
    return JsonResponse({"error": "false", "data": all_templates})


def create_category(request):
    """
    View to create category
    """
    if request.method == "GET":
        form = CreateCategoryForm()
        return render_to_response("create_category.html", {"form": form},
                                  context_instance=RequestContext(request))
    elif request.method == "POST":
        form = CreateCategoryForm(data=request.POST)
        if not form.is_valid():
            return render_to_response("create_category.html",
                                      {"form": form, "errors": form.errors},
                                      context_instance=RequestContext(request))
        try:
            category = Category.objects.create(
                        category_name=form.cleaned_data['category_name'],
                        description=form.cleaned_data['description'])
        except IntegrityError:
            message = "Category with the same name already exist"
            return render_to_response("create_category.html",
                                      {"form": form, "errors": message},
                                      context_instance=RequestContext(request))
        redirect_url = reverse('create-template')
        redirect_url += "?categ=%s" %(category.slug) 
        return HttpResponseRedirect(redirect_url)


def create_template_format(request):
    """
    View to create new template format.
    """
    if request.method == "GET":
        form = TemplateFormatForm()
        return render_to_response("create_format.html",
                                  {"form": form},
                                  context_instance=RequestContext(request))
    elif request.method == "POST":
        form = TemplateFormatForm(data=request.POST)
        if not form.is_valid():
            return render_to_response("create_format.html",
                                      {"form": form, "errors": form.errors},
                                      context_instance=RequestContext(request))

        category = get_object_or_404(Category,
                                     slug=form.cleaned_data['category'])
        try:
            template = TemplateFormat.objects.create(
                   category=category,
                   template_name=form.cleaned_data['template_name']
                   )
        except IntegrityError:
            message = "Template Name Already exist"
            return render_to_response("create_format.html",
                                      {"form": form, "errors": message},
                                      context_instance=RequestContext(request))
        redirect_url = reverse('upload_document')
        redirect_url += "?categ=%s&format=%s" %(category.slug, 
                                                 template.slug)
        return HttpResponseRedirect(redirect_url)


def upload_document(request):
    """
    View for handling document upload
    """
    if request.method == "GET":
        form = DocumentForm()
        return render_to_response("upload_document.html",
                                  {"form": form},
                                  context_instance=RequestContext(request))
    elif request.method == "POST":
        form = DocumentForm(request.POST, request.FILES)
        if not form.is_valid():
            return render_to_response("upload_document.html",
                                      {"form": form, "errors": form.errors},
                                      context_instance=RequestContext(request))

        template = get_object_or_404(TemplateFormat,
                                     slug=form.cleaned_data['template'])
        document = Document.objects.create(
                template_format=template,
                document_name=form.cleaned_data['document_name'],
                document=request.FILES['document']
        )
        return HttpResponseRedirect(
                reverse('particular_document',
                        kwargs={"unique_id": document.id}
                        ))


@csrf_exempt
def particular_document(request, unique_id):
    """
    View to display a particular document and let the end user to select
    elements from it on the frontend and save them
    """
    document = get_object_or_404(Document, id=unique_id)
    all_elements = document.template_format.templateelement_set.all()
    if request.method == "GET":
        if document.extractedelements_set.all().count() > 0 :
          return HttpResponseRedirect(reverse('preview_document',
                                      kwargs={"unique_id":document.id}))
        return render_to_response('document_selector.html',
                                  {"document": document,
                                   "elements": all_elements},
                                  context_instance=RequestContext(request))

    elif request.method == "POST":

        data = json.loads(json.loads(request.POST['data']))
        if document.image_resolution_x and document.image_resolution_y:
            pass
        else:
            document.image_resolution_x = data["image_width"]
            document.image_resolution_y = data["image_height"]
            document.save()
        template = document.template_format
        document.extractedelements_set.all().delete()
        for element_name in data["elements"]:
            element = TemplateElement.objects.get_or_create(
                    template=template, element_name=element_name)[0]

            extracted_element = ExtractedElements.objects.get_or_create(
                    document=document, element=element)[0]
            extracted_element.x1_coordinate = data[element_name]["x"]
            extracted_element.y1_coordinate = data[element_name]["y"]
            extracted_element.block_width = data[element_name]["width"]
            extracted_element.block_height = data[element_name]["height"]
            extracted_element.save()
        return JsonResponse({"error": "false",
                            "message": "Successfully saved elements"})


def all_documents(request):
    """
    View to display all documents
    """
    documents = Document.objects.all()
    if request.method == "GET":
        return render_to_response("all_documents.html",
                                  {"documents": documents},
                                  context_instance=RequestContext(request))


def document_preview(request, unique_id):
    """
    View to preview/ update a document. Any document for which the elements
    have been created is eligible for preview/ update
    """
    document = get_object_or_404(Document, id=unique_id)
    elements = document.template_format.templateelement_set.all()
    return render_to_response("document_elements.html",
                              {"document": document, "elements": elements},
                              context_instance=RequestContext(request))


def get_element_coordinates(request, unique_id, element):
    """
    Get approx coordinates of a particular element for a given template format
    Average of all values of the particular element for various documents is
    considered.  
    """
    try:
        document = Document.objects.get(id=unique_id)
    except Document.DoesNotExist:
        return JsonResponse({
            "error": "true",
            "message": "Document Does not exist"
            })
    template = document.template_format
    try:
        element = TemplateElement.objects.get(template=template,
                                              element_name__iexact=element)
    except TemplateElement.DoesNotExist:
        return JsonResponse({"error": "true",
                            "message": "Element Does not exist"})

    avg_x = ExtractedElements.objects.filter(
                    element=element).aggregate(Avg('x1_coordinate'))
    avg_y = ExtractedElements.objects.filter(
                    element=element).aggregate(Avg('y1_coordinate'))
    avg_height = ExtractedElements.objects.filter(
                    element=element).aggregate(Avg('block_height'))
    avg_width = ExtractedElements.objects.filter(
                    element=element).aggregate(Avg('block_width'))

    return JsonResponse({"error": "false", "x": avg_x, "y": avg_y,
                        "height": avg_height, "width": avg_width})

templates/all_documents.html
{%extends "base.html"%}
{%block head%}
<style>
.image{
    height:300px;
    background-size:100% 100% ;
}
</style>
<script type = "text/javascript">
$(document).ready(function(){
   $(".image").click(function(){
      //console.log($(this).parent().attr("id"));
      window.location = "/document/" + $(this).parent().attr("id");
   });
});
</script>
{%endblock%}
{%block main_block%}
{%for document in documents%}
<div class="col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1 col-md-3 col-lg-3 col-lg-offset-0 col-md-offset-0 document" id = "{{document.id}}">
    <div class = "image" style="background-image:url('/media/{{document.document}}')"></div>
    <div class = "">
        <h3>{{document.document_name}}</h3>
    </div>
</div>
{%endfor%}
{%endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    {%load static from staticfiles%}
    <link rel="stylesheet" href="{%static 'bootstrap/css/bootstrap.min.css'%}">
    <script type = "text/javascript" src = "{%static 'js/jquery.js'%}"></script>
    <script type = "text/javascript" src = "{%static 'bootstrap/js/bootstrap.min.js'%}"></script>
    <style>
      .errorlist{
        color:red;
      }
      ul.links{
          list-style:none;
          display:inline;
      }
      ul.links > li{
          display:inline;
          float:left;
          margin-left:30px;
          background-color:#337ab7;
          color:white;
          border-color:#2e6da4;
          line-height:1.42857143;
          text-align:center;
          border-radius:4px;
          border:1px solid transparent;
          padding:6px 12px;
      }
      ul.links > li > a{
          color:white
      }
      #ui-id-1{
        z-index:2000;
      }
    </style>
    {%block head%}{%endblock%}
</head>
<body>
{%block main_block%} 

{%endblock%}
<div class="col-sm-12 col-xs-12 col-md-6 col lg-6 col-md-offset-3 col-lg-offset-3" style = "margin-top:150px;">
    <ul class = "links">
        <li><a href="{%url 'create-category'%}">Add New Category</a></li>
        <li><a href="{%url 'create-template'%}">Add New Format</a></li>
        <li><a href="/upload-document">Upload Document</a></li>
    </ul>
</div>
</body>
</html>

templates/create_category.html
{%extends "base.html"%}

{%block main_block%}
<h1><center>Create Category</center></h1>
<form class = "form-horizontal col-sm-12 col-md-offset-4 col-lg-4 col-md-offset-4 col-lg-offset-4 col-xs-12" action = "{{request.path}}" method="post">
  {%csrf_token%}
  {{form.as_p}}
  <center><input type = "submit" value = "Create Category" class = "btn btn-primary col-sm-12"/></center>
</form>
{%endblock%}

templates/create_format.html
{%extends "base.html"%}

{%block main_block%}
<h1><center>Create Template format</center></h1>
<form class = "form-horizontal col-sm-12 col-md-offset-4 col-lg-4 col-md-offset-4 col-lg-offset-4 col-xs-12" action = "{{request.path}}" method="post" style = "margin-top:50px;">
  {%csrf_token%}
  <p style = "color:red">{{errors}}</p>
  {{form.as_p}}
  <center><input type = "submit" value = "Create Template Format" class = "btn btn-primary col-sm-12"/></center>
</form>
<p>
<a href="{%url 'create-category'%}">Create New Category</a>
</p>
<script>
$(document).ready(function(){
	var search_query = window.location["search"].split("&")
    var category = "";
    var template_name = "";
    if (search_query.length == 1 && search_query[0] == "")
    {
     console.log("No search query");
    }
    else{
     console.log("els");
     category = search_query[0].split("=")[1];
     console.log(category);
    }
	$("#id_category").val(category);
});
</script>
{%endblock%}

templates/document_elements.html
{%extends "base.html"%}
{%block head%}
<title>Demo Preview Selection</title>
{%include "initialize_variables_and_functions.html"%}


{%include "document_selector_static_files.html" %}
  
<script type = "text/javascript" >
  {%include "javascript_document_preview.html"%}
</script>
{%endblock%}
{%block main_block%}
   <div id="left" class = "col-sm-12 col-md-6 col-xs-12 col-lg-6">
    <section class="parent" style="overflow: hidden; position:relative" id = "focal">
        <div class="panzoom image-decorator" style=" cursor: move; transition: none;">
            <img src="/media/{{document.document}}" id = "example">
        </div>
      <script>
        (function() {
          //function controlling the zoom on the image
          var zoom_level = 0;
          var $section = $('#focal');
          var $panzoom = $section.find('.panzoom').panzoom();
          $panzoom.parent().on('mousewheel.focal', function( e ) {
            e.preventDefault();
            var delta = e.delta || e.originalEvent.wheelDelta;
            var zoomOut = delta ? delta < 0 : e.originalEvent.deltaY > 0;
            zoom_level += 1;
            $panzoom.panzoom('zoom', zoomOut, {
              increment: 0.1,
              focal: e, 
            });
          });           
        })();
      </script>
    </section>
   </div>
   <div class = "right" class = "col-sm-12 col-md-6 col-xs-12 col-lg-6">
       <label for="elements_available">Create new element</label>
       <select id="elements_available" name="" class = "dropdown form-control" style = "">
       </select>
       <select id="elements_used" name="" class = "dropdown form-control" style = "display:none">
       </select>
       <table class="table table-striped" class = "output" id = "output" style = "margin-top:30px">
       </table> 
       <button type = "button" class = "btn btn-primary" id = "submit">Update Selection</button>
   </div>
   <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Update Element Name</h4>
        </div>
        <div class="modal-body" style = "height:150px;">
          <input type = "hidden" name = "variable_id" id = "variable_id" class = "form-control">

          <p>
            <label for="variable_name">Enter Element Name:</label>
            <input type = "text" name = "variable_name" id = "variable_name" class = "form-control">
          </p>
          <p>
            <button type = "button"  class = "btn btn-primary col-sm-4" id = "save_element">Update Element Name
            </button>
          </p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        </div>
      </div>
    </div>
   </div>
   

   <script type = "text/javascript">

    
   
   </script>
{%endblock%}

templates/document_selector.html
{%extends "base.html"%}
{%block head%}
<title>Demo Select Areas</title>
{%include "initialize_variables_and_functions.html"%}


{%include "document_selector_static_files.html" %}
  
<script type = "text/javascript" >
  {%include "javascript_document_selector.html"%}
</script>
{%endblock%}
{%block main_block%}
   <div id="left" class = "col-sm-12 col-md-6 col-xs-12 col-lg-6">
    <section class="parent" style="overflow: hidden; position:relative" id = "focal">
        <div class="panzoom image-decorator" style=" cursor: move; transition: none;">
            <img src="/media/{{document.document}}" id = "example">
        </div>
      <script>
        (function() {
          //function controlling the zoom on the image
          var zoom_level = 0;
          var $section = $('#focal');
          var $panzoom = $section.find('.panzoom').panzoom();
          $panzoom.parent().on('mousewheel.focal', function( e ) {
            e.preventDefault();
            var delta = e.delta || e.originalEvent.wheelDelta;
            var zoomOut = delta ? delta < 0 : e.originalEvent.deltaY > 0;
            zoom_level += 1;
            $panzoom.panzoom('zoom', zoomOut, {
              increment: 0.1,
              focal: e, 
            });
          });           
        })();
      </script>
    </section>
   </div>
   <div class = "right" class = "col-sm-12 col-md-6 col-xs-12 col-lg-6">
   {%if elements.count == 0%} <div style = "display:none"> {%endif%}
       <label for="elements_available">Create new element</label>
       <select id="elements_available" name="" class = "dropdown form-control" style = "">
       </select>
    {%if elements.count == 0%} </div>{%endif%}
       <select id="elements_used" name="" class = "dropdown form-control" style = "display:none">
       </select>
       <table class="table table-striped" class = "output" id = "output" style = "margin-top:30px">
       </table> 
       <button type = "button" class = "btn btn-primary" id = "submit">Save Selection</button>
   </div>
   <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Update Element Name</h4>
        </div>
        <div class="modal-body" style = "height:150px;">
          <input type = "hidden" name = "variable_id" id = "variable_id" class = "form-control">

          <p>
            <label for="variable_name">Enter Category Name:</label>
            <input type = "text" name = "variable_name" id = "variable_name" class = "form-control">
          </p>
          <p>
            <button type = "button"  class = "btn btn-primary col-sm-4" id = "save_element">Update Element Name
            </button>
          </p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        </div>
      </div>
    </div>
   </div>
   

   <script type = "text/javascript">

    
   
   </script>
{%endblock%}

templates/document_selector_static_files.html
  {%load static from staticfiles%}

	<!--[if lte IE 8]>
      <link href="{%static 'css/jquery-select-areas/jquery.selectareas.ie8.css' %}" media="screen" rel="stylesheet" type="text/css" /> 
   <![endif]-->
  <link rel="stylesheet" href="{%static 'css/jquery-ui.css' %}">
  <script src="{%static 'js/jquery-1.10.2.js' %}"></script>
  <script src="{%static 'js/jquery-ui.js' %}"></script>

  <link href="{%static 'css/example.css' %}" media="screen" rel="stylesheet" type="text/css" />
  <link href="{%static 'css/jquery-select-areas/jquery.selectareas.css' %}" media="screen" rel="stylesheet" type="text/css" />
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

  <script type = "text/javascript" src = "{%static 'js/base.js' %}"></script>
  <script type = "text/javascript" src = "{%static 'bootstrap/js/bootstrap.min.js' %}"></script>
  <script type = "text/javascript" src = "{%static 'js/jquery-panzoom/jquery.panzoom.js' %}"></script>
  
  <script type = "text/javascript" src = "{%static 'js/jquery-select-areas/jquery.selectareas.js' %}"></script>
  

templates/initialize_variables_and_functions.html
<script type = "text/javascript" >

  //initialise elements_available from the elements that exist for the 
  //template of given document
  

  var elements_available =  [  {%for element in elements%} "{{element.element_name}}" {%if not forloop.last%},{%endif%} {%endfor%}     ];
  //initialise other variables
  var elements_used = [];
  var element_rectangle = {};
  var boxes_count = 0;
//      localStorage.setItem("boxes_count", boxes_count);  

  function create_rectangle_selection(x, y, width, height)
  {
    /*
        function to create rectangular selection
    */
    var areaOptions = {
        x: x,
        y: y,
        width: width,
        height: height,
    };
    //call the function to initialise the rectangle_box with areaOptions
    $('img#example').selectAreas('add', areaOptions);   
  }

  //set variables to local storage  
  function update_local_storage_variables(elements_available, elements_used, element_rectangle, boxes_count)
  {
    localStorage.setItem("elements_available", JSON.stringify(elements_available));
    localStorage.setItem("elements_used", JSON.stringify(elements_used));
    localStorage.setItem("element_rectangle", JSON.stringify(element_rectangle));
    localStorage.setItem("boxes_count", boxes_count);
  }
  
  //function to update_elements of dropdown select box
  function update_elements_tables(array_name, id){
      var all_options = "<option value='----'>-----</option> ";            
      $.each(array_name, function(key, value){
        var option_string = "<option value='" + value  + "'>" + value + "</option> " ;
        all_options += option_string ;
      });
      $("#"+ id).html(all_options);
  }
  
  //autocomplete : autosuggest
  function autosuggest(element_available){
    $( "#variable_name" ).autocomplete({
      source: elements_available
    });    
  }

</script>

templates/upload_document.html
{%extends "base.html"%}

{%block main_block%}
<h1>
    <center>Upload Document</center>
</h1>
<div class="col-sm-12 col-xs-12 col-md-offset-4 col-lg-offset-4 col-lg-4 col-md-4">
    
</div>
<form class = "form-horizontal col-sm-12 col-md-offset-4 col-lg-4 col-md-offset-4 col-lg-offset-4 col-xs-12" action = "{{request.path}}" method="post" enctype="multipart/form-data" style = "margin-top:50px">
  {%csrf_token%}
  {{form.as_p}}
  <input type = "submit" value = "Upload Document" class = "btn btn-primary col-sm-12"/>
</form>
<script type = "text/javascript">
    $("#id_category").change(function(){
        console.log("change");
        update_template_list();
    });

  $(document).ready(function(){
    update_template_list(fresh=true);

  });
  function update_template_list(fresh=false, template="" ){
     var category = $("#id_category").val();
     console.log("category = "+ category);
     $.get("/get_template/"+ category, function(data){
        if(data["error"] == "true")
        {
           alert(data["message"]);
        }
        else{
           console.log("inside el");
           str = JSON.parse(data["data"]);
           new_rows = "";
           for(i=0; i<str.length; i++)
           {
               new_row_string = '<option value="' + str[i]["fields"]["slug"] + '">' + 
                   str[i]["fields"]["template_name"]+'</option>';
               new_rows += new_row_string;
           }
           $("#id_template").html(new_rows);
           if(fresh!=false)
           {
               var search_query = window.location["search"].split("&")
               var category = "";
               var template_name = "";
               if (search_query.length == 1 && search_query[0] == ""){}
               else{
                category = search_query[0].split("=")[1];
                template_name = search_query[1].split("=")[1];
                console.log(template_name);
               }
               $("#id_category").val(category);
               update_template_list(fresh=false, template=template_name);           
           }
           if(template != "")
           {
              $("#id_template").val(template);
           }
        }
    });
}
</script>
{%endblock%}